#!/usr/bin/env bash

if [ "$0" = "$BASH_SOURCE" ]; then
	echo "You must source this script. Try: source pp-activate $1" >&2
	exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/pp-common"

if [ ! -z "$1" ]; then
	env_name="$1"
elif [ -f '.pp' ]; then
	env_name=$(cat .pp)
else
	env_name=${PWD##*/}
fi

if [ ! -d "${PP_ENVS_DIR}/$env_name" ]; then
	echo "Virtual env not found: $env_name"
	return 1
fi

source "${PP_ENVS_DIR}/$env_name/bin/activate"