#!/usr/bin/env bash

if [ "$0" = "$BASH_SOURCE" ]; then
	echo "You must source this script. Try: source pp-activate $1" >&2
	exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/pp-common"

if [ ! -z "$1" ]; then
	env_name="$1"
elif [ -f ${PP_NAME_FILE} ]; then
	env_name=$(cat ${PP_NAME_FILE})
else
	env_name=${PWD##*/}
fi

if [ ! -d "${PP_ENVS_DIR}/$env_name" ]; then
	echo "Virtual env not found: $env_name"
	return 1
fi

BIN_DIR="${PP_ENVS_DIR}/$env_name/bin/"
if [ ! -d "$BIN_DIR" ]; then
	BIN_DIR="${PP_ENVS_DIR}/$env_name/Scripts/"
fi

if [ ! -d "$BIN_DIR" ]; then
	echo "Couldn't find the activate script inside '${PP_ENVS_DIR}/$env_name/'" >&2
	exit 1
fi	

source "${BIN_DIR}/activate"