#!/usr/bin/env bash

[ -z "${PP_ENVS_DIR}" ] && PP_ENVS_DIR="${HOME}/.pyvenv"
[ -z "${PP_NAME_FILE}" ] && PP_NAME_FILE=".papy"

list() {
	if [[ ! -f ${PP_ENVS_DIR} ]]; then
		return
	fi
	( cd ${PP_ENVS_DIR} ; ls -d */ | cut -f1 -d'/' )
}